"""Private request attachments; never expose the storage directory as static files."""
import re
from pathlib import Path
from uuid import uuid4

from fastapi import HTTPException
from app.utils.config import get_settings

MAX_FILE_BYTES = 5 * 1024 * 1024
MAX_REQUEST_BYTES = 2 * MAX_FILE_BYTES + 128 * 1024


def validate_attachment(kind, name, content):
    name = (name or "").replace("\\", "/").split("/")[-1]
    name = "".join(c for c in name if c.isprintable()).strip()[:255]
    suffix = Path(name).suffix.lower()
    if not content or len(content) > MAX_FILE_BYTES:
        raise HTTPException(422, "Lampiran harus berisi data dan maksimal 5 MB per file.")
    mime = None
    if suffix in (".jpg", ".jpeg") and content.startswith(b"\xff\xd8\xff"):
        mime = "image/jpeg"
    elif suffix == ".png" and content.startswith(b"\x89PNG\r\n\x1a\n"):
        mime = "image/png"
    elif kind == "electricity_bill" and suffix == ".pdf" and content.startswith(b"%PDF-"):
        mime = "application/pdf"
    if mime is None:
        raise HTTPException(422, "Format lampiran tidak sesuai. Foto atap: JPG/PNG; struk PLN: JPG/PNG/PDF.")
    return {"kind": kind, "name": name, "mime": mime, "content": content}


def private_file_path(key):
    # Storage keys are generated by the server, never taken from a filename/URL.
    if not re.fullmatch(r"[a-f0-9]{32}", key):
        raise HTTPException(404, "Lampiran tidak ditemukan.")
    return get_settings().upload_dir.resolve() / key


def store_attachment(attachment):
    key = uuid4().hex
    path = private_file_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    created = False
    try:
        with path.open("xb") as output:
            created = True
            output.write(attachment["content"])
    except Exception:
        if created:
            path.unlink(missing_ok=True)
        raise
    return key
